using SciMLTesting, DASSL, Test

# Keep this snapshot fixed so new DiffEqBase exports fail QA instead of becoming DASSL API.
const DIFFEQBASE_REEXPORTS = (
    :AbstractAnalyticalProblem,
    :AddVector,
    :AffineOperator,
    :AllObserved,
    :AnalyticalProblem,
    :BVPFunction,
    :BVProblem,
    :BatchIntegralFunction,
    :BlockDiagonalOperator,
    :BrownFullBasicInit,
    :CallbackSet,
    :CheckInit,
    :Clocks,
    :ContinuousCallback,
    :ConvexOptimizationProblem,
    :DAEFunction,
    :DAEProblem,
    :DAESolution,
    :DDEFunction,
    :DDEProblem,
    :DEAlgorithm,
    :DEProblem,
    :DESolution,
    :DEVerbosity,
    :DefaultInit,
    :DiagonalOperator,
    :DiffEqBase,
    :DiscreteCallback,
    :DiscreteFunction,
    :DiscreteProblem,
    :DynamicalBVPFunction,
    :DynamicalDDEFunction,
    :DynamicalDDEProblem,
    :DynamicalODEFunction,
    :DynamicalODEProblem,
    :DynamicalSDEFunction,
    :DynamicalSDEProblem,
    :EigenvalueProblem,
    :EigenvalueSolution,
    :EigenvalueTarget,
    :EnsembleAnalysis,
    :EnsembleContext,
    :EnsembleDistributed,
    :EnsembleProblem,
    :EnsembleSerial,
    :EnsembleSolution,
    :EnsembleSplitThreads,
    :EnsembleSummary,
    :EnsembleTestSolution,
    :EnsembleThreads,
    :FunctionOperator,
    :HomotopyNonlinearFunction,
    :HomotopyProblem,
    :IdentityOperator,
    :ImplicitDiscreteFunction,
    :ImplicitDiscreteProblem,
    :IncrementingODEFunction,
    :IncrementingODEProblem,
    :IntegralFunction,
    :IntegralProblem,
    :IntegralSolution,
    :IntervalNonlinearFunction,
    :IntervalNonlinearProblem,
    :InvertibleOperator,
    :LinearAliasSpecifier,
    :LinearProblem,
    :LinearSolution,
    :MatrixOperator,
    :MultiObjectiveOptimizationFunction,
    :NoInit,
    :NoiseProblem,
    :NonlinearFunction,
    :NonlinearLeastSquaresProblem,
    :NonlinearProblem,
    :NonlinearSolution,
    :NullOperator,
    :ODEAliasSpecifier,
    :ODEFunction,
    :ODEInputFunction,
    :ODEProblem,
    :ODESolution,
    :OptimizationFunction,
    :OptimizationProblem,
    :OptimizationSolution,
    :OverrideInit,
    :PDENoTimeSolution,
    :PDEProblem,
    :PDETimeSeriesSolution,
    :QuadratureProblem,
    :QuadratureSolution,
    :RODEFunction,
    :RODEProblem,
    :RODESolution,
    :ReturnCode,
    :SCCNonlinearProblem,
    :SDDEFunction,
    :SDDEProblem,
    :SDEFunction,
    :SDEProblem,
    :SampledIntegralProblem,
    :ScalarOperator,
    :SciMLAlgorithm,
    :SciMLBase,
    :SciMLOperators,
    :SciMLSolution,
    :SecondOrderBVProblem,
    :SecondOrderDDEProblem,
    :SecondOrderODEProblem,
    :SensitivityADPassThrough,
    :ShampineCollocationInit,
    :SplitFunction,
    :SplitODEProblem,
    :SplitSDEFunction,
    :SplitSDEProblem,
    :StaticWOperator,
    :SteadyStateProblem,
    :SteadyStateSolution,
    :TensorProductOperator,
    :TensorSumOperator,
    :TimeChoiceIterator,
    :TimeDomain,
    :TwoPointBVPFunction,
    :TwoPointBVProblem,
    :TwoPointDynamicalBVPFunction,
    :TwoPointSecondOrderBVProblem,
    :VectorContinuousCallback,
    :WOperator,
    :add_saveat!,
    :add_tstop!,
    :addat!,
    :addat_non_user_cache!,
    :addsteps!,
    :auto_dt_reset!,
    :cache_operator,
    :change_t_via_interpolation!,
    :check_error,
    :check_keywords,
    :concrete_solve,
    :concretize,
    :deleteat!,
    :deleteat_non_user_cache!,
    :derivative_discontinuity!,
    :discretize,
    :du_cache,
    :fastpow,
    :finalize!,
    :first_tstop,
    :full_cache,
    :get_dt,
    :get_du,
    :get_du!,
    :get_proposed_dt,
    :get_rng,
    :get_tmp_cache,
    :has_adjoint,
    :has_concretization,
    :has_exp,
    :has_expmv,
    :has_expmv!,
    :has_ldiv,
    :has_ldiv!,
    :has_mul,
    :has_mul!,
    :has_rng,
    :has_tstop,
    :init,
    :initialize!,
    :intervals,
    :is_discrete_time_domain,
    :iscached,
    :isclock,
    :isconstant,
    :iscontinuous,
    :isconvertible,
    :isdiscrete,
    :isinplace,
    :islinear,
    :issolverstepclock,
    :issquare,
    :kronsum,
    :pop_tstop!,
    :rand_cache,
    :ratenoise_cache,
    :reeval_internals_due_to_modification!,
    :reinit!,
    :remake,
    :resize_non_user_cache!,
    :savevalues!,
    :set_abstol!,
    :set_proposed_dt!,
    :set_reltol!,
    :set_rng!,
    :set_t!,
    :set_u!,
    :solve,
    :solve!,
    :step!,
    :supports_solve_rng,
    :symbolic_discretize,
    :terminate!,
    :tuples,
    :u_cache,
    :u_modified!,
    :update_coefficients,
    :update_coefficients!,
    :user_cache,
    :warn_compat,
)

const DIFFEQBASE_MODULE_REEXPORTS = (
    :Clocks,
    :DiffEqBase,
    :EigenvalueTarget,
    :EnsembleAnalysis,
    :ReturnCode,
    :SciMLBase,
    :SciMLOperators,
)

const DIFFEQBASE_RENDERED_IGNORE = Tuple(
    name for name in DIFFEQBASE_REEXPORTS if name ∉ DIFFEQBASE_MODULE_REEXPORTS
)

run_qa(
    DASSL;
    reexports_allow = DIFFEQBASE_REEXPORTS,
    api_docs_kwargs = (; rendered_ignore = DIFFEQBASE_RENDERED_IGNORE),
    ei_kwargs = (;
        all_explicit_imports_are_public = (;
            ignore = (
                :_process_verbose_param,    # DiffEqBase
            ),
        ),
    )
)

@testset "Type Stability" begin
    alg = dassl()
    @test typeof(alg.maxorder) === Int
    @test typeof(alg.factorize_jacobian) === Bool

    y0 = [1.0, 2.0]
    cache = DASSL.alg_cache(alg, y0, nothing, 0.0, Val(true))
    @test isconcretetype(typeof(cache.jac_factorized))
    @test !(cache.jac_factorized isa Any && typeof(cache.jac_factorized) === Any)
end

include(joinpath(@__DIR__, "..", "shared", "alloc_tests.jl"))
